[tool]
id = "com.thelightphone.brighthome"
label = "Home"
versionCode = 1
versionName = "1.0.0"
permissions = ["android.permission.INTERNET", "android.permission.ACCESS_NETWORK_STATE", "android.permission.CAMERA", "android.permission.VIBRATE"]
# Running on the LightOS emulator? swap the serverPackage below:
# serverPackage = "com.thelightphone.sdk.emulator"
serverPackage = "com.lightos"
